bav/urls.py
from django.urls import path

from . import views

app_name = 'bav'
urlpatterns = [
    path('', views.index, name='index'),
    path('bav', views.BAVListView.as_view(), name='bav_list'),
    path('bav/<int:bav_id>/sell', views.sell, name='sell'),
    path('bav/<int:bav_id>/pay', views.bav_pay, name='bav_pay'),
    path('sale/<int:pk>', views.SaleDetailView.as_view(), name='sale_detail'),
    path('sale/<int:sale_id>/pay', views.pay, name='pay'),
]

bavpower/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('bav.urls')),
    path('stats/', include('stats.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
]

stats/urls.py
from django.urls import path

from . import views

app_name = 'stats'
urlpatterns = [
    path('bav/<int:bav_id>', views.index, name='index'),
]

bav/models.py
from django.db import models

class BAV(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return '{}'.format(self.name)

class Seller(models.Model):
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    email = models.EmailField()
    slug = models.SlugField(max_length=5, unique=True)
    is_adherent = models.BooleanField()
    is_board_member = models.BooleanField()

    def __str__(self):
        return '{} {}'.format(self.firstname, self.lastname)

class Sale(models.Model):
    bav = models.ForeignKey(BAV, on_delete=models.CASCADE)
    date = models.DateTimeField()
    client = models.CharField(max_length=30)
    is_adherent = models.BooleanField()
    is_board_member = models.BooleanField()
    payment_method = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self):
        return '{} - {} - {}'.format(self.id, self.bav.name, self.client, )

class SaleItem(models.Model):
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    article_id = models.PositiveSmallIntegerField()

    def __str__(self):
        return '{} - {} - {}'.format(self.id, self.seller, self.price)

stats/models.py
from django.db import models

# Create your models here.

bav/views.py
import datetime
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import PermissionRequiredMixin

from .form import PaymentForm, SaleForm, SaleItemForm

from .models import BAV, Sale, SaleItem

def index(request):
    return HttpResponseRedirect(reverse('bav:bav_list'))

class BAVListView(PermissionRequiredMixin, ListView):
    model = BAV
    permission_required = 'bav.view_bav'

@permission_required('bav.add_sale')
def sell(request, bav_id):
    bav = BAV.objects.get(pk=bav_id)
    SaleItemFormSet = inlineformset_factory(Sale, SaleItem, form=SaleItemForm, extra=50, can_delete=False)

    form = SaleForm()
    sale = Sale()
    formset = SaleItemFormSet(instance=sale)

    if request.method == 'POST':
        form = SaleForm(request.POST)

        if form.is_valid():
            sale = form.save(commit=False)
            sale.bav = bav
            sale.date = datetime.datetime.now()
            formset = SaleItemFormSet(request.POST, instance=sale)

            if formset.is_valid():
                sale.save()
                formset.save()

                return HttpResponseRedirect(reverse('bav:sale_detail', args=(sale.id,)))

    return render(request, 'bav/sell.html', {'bav': bav, 'form': form, 'formset': formset})

@permission_required('bav.change_sale')
def pay(request, sale_id):
    sale = Sale.objects.get(pk=sale_id)
    form = PaymentForm(instance=sale)

    if request.method == 'POST':
        form = PaymentForm(request.POST)

        if form.is_valid():
            sale.payment_method = form.cleaned_data['payment_method']
            sale.save()

            return HttpResponseRedirect(reverse('bav:sale_detail', args=(sale.id,)))

    return render(request, 'bav/pay.html', {'sale': sale, 'form': form })

@permission_required('bav.change_sale')
def bav_pay(request, bav_id):
    bav = BAV.objects.get(pk=bav_id)
    sales = Sale.objects.filter(bav=bav, payment_method__isnull=True)

    return render(request, 'bav/bav_pay.html', {'bav': bav, 'sales': sales})

class SaleDetailView(PermissionRequiredMixin, DetailView):
    model = Sale
    permission_required = 'bav.view_sale'

stats/views.py
import decimal
from django.db.models.aggregates import Count, Sum
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required

from bav.models import BAV, Sale, SaleItem, Seller

@permission_required('bav.view_bav')
def index(request, bav_id):
    bav = BAV.objects.get(pk=bav_id)

    payment_methods = []
    for payment_method in Sale.objects.values('payment_method').distinct():
        payment_method['count'] = Sale.objects.filter(payment_method=payment_method['payment_method']).count()
        payment_method['sum'] = SaleItem.objects.filter(sale__payment_method=payment_method['payment_method']).aggregate(Sum('price'))['price__sum']
        payment_methods.append(payment_method)

    sellers = []
    for seller in Seller.objects.all().order_by('slug'):
        s = {}
        s['firstname'] = seller.firstname
        s['lastname'] = seller.lastname
        s['slug'] = seller.slug
        s['is_adherent'] = seller.is_adherent
        s['is_board_member'] = seller.is_board_member
        s['amount'] = SaleItem.objects.filter(seller=seller).aggregate(Sum('price'))['price__sum']
        s['items'] = SaleItem.objects.filter(seller=seller).values('article_id').order_by('article_id')

        if seller.is_adherent:
            s['profit'] = s['amount'] * decimal.Decimal(0.85)
        elif seller.is_board_member:
            s['profit'] = s['amount'] * decimal.Decimal(0.90)
        else:
            s['profit'] = s['amount'] * decimal.Decimal(0.80)

        sellers.append(s)

    return render(request, 'stats/index.html', {
        'bav': bav,
        'payment_methods': payment_methods,
        'sellers': sellers,
    })

bav/templates/bav/bav_list.html
{% extends "base.html" %}

{% block content %}
  <ul class="list-group">
    {% for bav in object_list %}
      <li class="list-group-item">
        <div class="row">
          <div class="col d-flex align-items-center">
              {{ bav.name }}
          </div>
          <div class="col-md-auto d-flex align-items-center">
            <div class="btn-group btn-group-sm float-end" role="group">
              <a href="{% url "bav:sell" bav.id %}" class="btn btn-outline-primary">Vendre</a>
              <a href="{% url "bav:bav_pay" bav.id %}" class="btn btn-outline-primary">Payer</a>
              <a href="{% url "stats:index" bav.id %}" class="btn btn-outline-primary">Resultat</a>
            </div>
          </div>
        </div>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

bav/templates/bav/bav_pay.html
{% extends "base.html" %}

{% block content %}
  <ul class="list-group">
    {% for sale in sales %}
      <li class="list-group-item">
        <div class="row">
          <div class="col d-flex align-items-center">
              {{ sale.client }}
          </div>
          <div class="col-md-auto d-flex align-items-center">
            <div class="btn-group btn-group-sm float-end" role="group">
              <a href="{% url "bav:pay" sale.id %}" class="btn btn-outline-primary">Payer</a>
            </div>
          </div>
        </div>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

bav/templates/bav/pay.html
{% extends "base.html" %}

{% block content %}
  <form action="{% url 'bav:pay' sale.id %}" method="post" class="form">
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    <div class="card">
      <div class="card-body">
        <div class="mb-3">
          {{ form.payment_method.errors }}
          <label for="{{ form.payment_method.id_for_label }}" class="form-label">Paiement method:</label>
          {{ form.payment_method }}
        </div>
        <div class="mb-3"> 
          <input type="submit" class="btn btn-primary" value="Payer" />
        </div>
      </div>
    </div>
  </form>
{% endblock %}

bav/templates/bav/sale_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <div class="card-title">
        <h1>{{ object.bav.name }} / {{ object.client }}</h1>
      </div>

      <ul class="list-group list-group-flush">
        <li class="list-group-item">BAV ID: {{ object.bav.id }}</li>
        <li class="list-group-item">{{ object.date }}</li>
        <li class="list-group-item">Adherent: {{ object.is_adherent }}</li>
        <li class="list-group-item">Membre du CA: {{ object.is_board_member }}</li>
        <li class="list-group-item">Paiement methode: {{ object.payment_method }}</li>
      </ul>
    </div>
  </div>

  <hr />

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Vendeur</th>
        <th scope="col">Prix</th>
        <th scope="col">Article ID</th>
      </tr>
    </thead>
    <tbody>
      {% for item in object.saleitem_set.all %}
        <tr>
          <td>{{ item.seller.firstname }} {{ item.seller.lastname }}</td>
          <td>{{ item.price }}</td>
          <td>{{ item.article_id }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <hr />

  <p>
    <a href="{% url "bav:sell" object.bav.id %}" class="btn btn-primary">Nouvelle vente</a>
  </p>
{% endblock %}

bav/templates/bav/sell.html
{% extends "base.html" %}

{% block content %}
  <form action="{% url 'bav:sell' bav.id %}" method="post" class="form">
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}


    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Informations sur la vente</h5>
        <div class="row justify-content-md-center">
          <div class="col">
            {{ form.client.errors }}
            <label for="{{ form.client.id_for_label }}" class="form-label">Client:</label>
            {{ form.client }}
          </div>
          <div class="col-md-auto d-flex align-items-center">
            <input type="submit" class="btn btn-primary" value="Vendre" />
          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="form-check form-check-inline">
              {{ form.is_adherent.errors }}
              <label for="{{ form.is_adherent.id_for_label }}" class="form-check-label">Adherent:</label>
              {{ form.is_adherent }}
            </div>
            <div class="form-check form-check-inline">
              {{ form.is_board_member.errors }}
              <label for="{{ form.is_board_member.id_for_label }}" class="form-check-label">Membre du CA:</label>
              {{ form.is_board_member }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <hr />

    {{ formset.management_form }}
    {% for hidden in formset.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    {% for article in formset %}
      <div class="row">
        {% for hidden in article.hidden_fields %}
          {{ hidden }}
        {% endfor %}

        <div class="col">
          {{ article.seller.errors }}
          <label for="{{ article.seller.id_for_label }}" class="form-label">Vendeur:</label>
          {{ article.seller }}
        </div>
        <div class="col">
          {{ article.price.errors }}
          <label for="{{ article.price.id_for_label }}" class="form-label">Prix:</label>
          {{ article.price }}
        </div>
        <div class="col">
          {{ article.article_id.errors }}
          <label for="{{ article.article_id.id_for_label }}" class="form-label">Article ID:</label>
          {{ article.article_id }}
        </div>
      </div>
    {% endfor %}
  </form>
{% endblock %}

stats/templates/stats/index.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ bav.name }}</h1>

  <h2>Methodes de paiement</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Methode</th>
        <th scope="col">Nombre de ventes</th>
        <th scope="col">Montant total</th>
      </tr>
    </thead>
    <tbody>
      {% for payment in payment_methods %}
        <tr>
          <td>{{ payment.payment_method }}</td>
          <td>{{ payment.count }}</td>
          <td>{{ payment.sum }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <h2>Vendeur</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Vendeur</th>
        <th scope="col">Nombre de vente</th>
        <th scope="col">Articles</th>
        <th scope="col">Montant total</th>
        <th scope="col">Gain</th>
      </tr>
    </thead>
    <tbody>
      {% for seller in sellers %}
        <tr>
          <td>{{ seller.slug }}</td>
          <td>
            <span class="position-relative">
              {{ seller.firstname }} {{ seller.lastname }}
              {% if seller.is_adherent %}
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-secondary">Adh</span>
              {% elif seller.is_board_member %}
                <span class="badge bg-primary">CA</span>
              {% endif %}
            </span>
          </td>
          <td>{{ seller.items.count }}</td>
          <td>
            {% for item in seller.items %}
              <span class="badge rounded-pill bg-light text-dark">{{ item.article_id }}</span> 
            {% endfor %}
          </td>
          <td>{{ seller.amount|floatformat:2 }}</td>
          <td>{{ seller.profit|floatformat:2 }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>BAV Power</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
        </ol>
      </nav>

      {% block content %} {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>